### ISSUE TITLE
complete function of todo with design

### ISSUE THREAD

**Issue by rishabh1403** [rishabh1403/MyLifeManager#8]
here is the list of tasks

- [x] save todo

- [x] complete

- [x] delete

- [x] show loading for all three

- [x] after each db operation fetch todo again

- [x] make responsive

- [x] control animation

- [x] use token not email

- [x] clean up

**Comment by rishabh1403** [comment]
after all operation i am fetching todo again because checkbox doesn't play well with ng-model
